finish post new comment
li-wang-uk/nc-news pull request #6
Opened 2023-12-13 15:35 UTC by li-wang-uk

2023-12-13 15:57 UTC, nc-verity-gregory requested changes
This is very close. I don't think your comments are being optimistically rendered, on a slow connection it takes time to see that something has happened. I do like that you clear the comment box though so I can't spam the submit button.

Some other comments to consider. Resubmit when you get your comments coming in optimistically.

2023-12-13 15:57 UTC, nc-verity-gregory commented on components/NewComment.jsx
> +                <input className="new-comment" type="text" placeholder = "Please input your comment here" onChange ={handleChange} value ={input}/>
This would be better if you changed it to a text area to support multi line comments.

2023-12-13 15:57 UTC, nc-verity-gregory commented on components/NewComment.jsx
> +        .catch((err) => {
I really like this.

2023-12-14 09:46 UTC, nc-modou reviewed
Comment submission works great! The only problem is that if a comment post fails, the optimistically rendered comment is still there. Please implement some logic to make this not show in the case of an unsuccessful comment post.

2023-12-14 10:16 UTC, nc-verity-gregory approved these changes
Really good refactor, nice work.

2023-12-14 10:18 UTC, merged